apiVersion: v1
kind: Service
metadata:
  name: my-deployment-service
  labels:
    app: cookies-webpage-deployment
    tier: front-end
spec:
  type: LoadBalancer
  selector:
    app: cookies-webpage-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
